import { ReconciliationData } from "@/components/portfolio/parsing/types";
import { MOCK_RECONCILIATION_DATA } from "@/components/portfolio/parsing/mockData";
import { Template } from "@/stores/templateStore";
import { VirtualFileSystem, normalizeBackendFiles } from "@/components/builder/fileStore";

/**
 * Simulates resume parsing API
 */
export const simulateResumeParsing = async (file: File): Promise<ReconciliationData> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            console.log("Simulated: Resume parsed", file.name);
            // We return a slightly modified version of the mock data to show it "worked"
            resolve({
                ...MOCK_RECONCILIATION_DATA,
                personalDetails: {
                    ...MOCK_RECONCILIATION_DATA.personalDetails,
                    fullName: "Alex Chen",
                }
            });
        }, 2000);
    });
};

/**
 * Simulates portfolio generation API
 */
export const simulatePortfolioGeneration = async (
    reconciliationData: ReconciliationData,
    template: Template
): Promise<VirtualFileSystem> => {
    return new Promise((resolve) => {
        setTimeout(() => {
            console.log("Simulated: Portfolio generated for", template.id);

            // Ensure files are in VFS format
            let generatedFiles: VirtualFileSystem;
            const files = template.files as any;
            const firstFile = Object.values(files)[0];

            if (typeof firstFile === "string") {
                generatedFiles = normalizeBackendFiles(files);
            } else {
                generatedFiles = { ...files };
            }

            // Dynamic generation logic: Inject resume data into portfolioData.js
            const dataFileContent = `
export const portfolioData = {
    name: "${reconciliationData.personalDetails.fullName}",
    role: "${reconciliationData.experience[0]?.role || 'Professional'}",
    bio: "${reconciliationData.personalDetails.summary}",
    skills: ${JSON.stringify(reconciliationData.skills)},
    projects: [
        { title: "AI Portfolio", description: "Project generated by Portfolio Automation Tool" },
        { title: "Legacy Work", description: "Experience at ${reconciliationData.experience[0]?.company || 'Previous Co'}" }
    ],
    socialLinks: { 
        github: "${reconciliationData.personalDetails.github}", 
        linkedin: "${reconciliationData.personalDetails.linkedin}" 
    }
};
            `.trim();

            const dataPath = Object.keys(generatedFiles).find(p => p.includes("portfolioData.js")) || "/src/portfolioData.js";
            generatedFiles[dataPath] = {
                code: dataFileContent,
                language: "javascript"
            };

            resolve(generatedFiles);
        }, 2500);
    });
};
